@WebApi_HostAddress = https://localhost:7275/api

GET {{WebApi_HostAddress}}/home/
Accept: application/json

###

POST {{WebApi_HostAddress}}/home/
Content-Type: application/json

{
  "Name": "UsmanCode 02"
}
###

PUT {{WebApi_HostAddress}}/home/
Content-Type: application/json

{
  "Id": 22,
  "Name": "UsmanCode 22"
}
###
