@WebApi_HostAddress = https://localhost:7275/api

GET {{WebApi_HostAddress}}/Users/
Accept: application/json

###

POST {{WebApi_HostAddress}}/Users/
Content-Type: application/json

{
  "Name": "UsmanCode 02",
  "UserAdressModel" : {
  "AdressLine1": "abc"
  }
}
###

PUT {{WebApi_HostAddress}}/home/
Content-Type: application/json

{
  "Id": 24,
  "Name": "UsmanCode 24"
}
###

DELETE {{WebApi_HostAddress}}/home/
Content-Type: application/json


 24

