@WebApi_HostAddress = https://localhost:7275

GET {{WebApi_HostAddress}}/api/home/
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/home/
Content-Type: application/json

{
  "Name": "Usman Rafiq"
}

###
